name: 'devkitpro-action'
description: 'Compile your project using devkitpro'
inputs:
  update-libnx:
    description: '1 to update libnx'
    required: false
    default: '0'
  cmd:
    description: 'Command line to execute'
    require: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.update-libnx }}
    - ${{ inputs.cmd }}
